on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - 1.19.x
        platform:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Report coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.txt
        fail_ci_if_error: true
